apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  db-username: {{ .Values.mysql.username | b64enc }}
  db-password: {{ "musee_password" | b64enc }}
