server.port=8085
logging.level.org=INFO

# Spring application
spring.application.name=projet1

# Database - MySQL sur Kubernetes
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysql-service:3306/musee_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=musee_user
spring.datasource.password=musee_password

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.data.jpa.repositories.enabled=true
spring.main.allow-bean-definition-overriding=true
spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB

# Application Insights - Monitoring Azure
azure.application-insights.instrumentation-key=384c93bc-0d78-4bcd-999d-85317661c47a
azure.application-insights.enabled=true
