trigger:
  branches:
    include:
      - main

variables:
  acrName: 'acrmuseevirtuel'
  imageName: 'projet1'
  imageTag: '$(Build.BuildId)'
  namespace: 'springapp-prod'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Login to ACR
      inputs:
        azureSubscription: 'AZURE_SERVICE_CONNECTION_NAME'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

    - script: |
        docker build -t $(acrName).azurecr.io/$(imageName):$(imageTag) ./projet1-main
        docker push $(acrName).azurecr.io/$(imageName):$(imageTag)
      displayName: Build and Push Image

- stage: Deploy
  displayName: Deploy to Kubernetes with Helm
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        helm upgrade --install springapp ./helm/springapp \
          --namespace $(namespace) \
          --set image.repository=$(acrName).azurecr.io/$(imageName) \
          --set image.tag=$(imageTag) \
          --set imagePullSecrets[0].name=acr-secret
      displayName: Helm Deploy
